In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("fifa_countries_audience.csv")

In [3]:
dataset.head()

,country,confederation,population_share,tv_audience_share,gdp_weighted_share
0,United States,CONCACAF,4.5,4.3,11.3
1,Japan,AFC,1.9,4.9,9.1
2,China,AFC,19.5,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4

In [4]:
#renaming column value
dataset.rename(columns={'tv_audience_share': 'audience_share'})

,country,confederation,population_share,audience_share,gdp_weighted_share
0,United States,CONCACAF,4.5,4.3,11.3
1,Japan,AFC,1.9,4.9,9.1
2,China,AFC,19.5,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4
...,...,...,...,...,...
186,Tonga,OFC,0.0,0.0,0.0
187,Liberia,CAF,0.1,0.0,0.0
188,Palau,OFC,0.0,0.0,0.0
189,Nauru,OFC,0.0,0.0,0.0
190,Niue,OFC,0.0,0.0,0.0

In [6]:
#renaming row index
dataset.rename(index={0: 'firstEntry', 1: 'secondEntry'})

,country,confederation,population_share,tv_audience_share,gdp_weighted_share
firstEntry,United States,CONCACAF,4.5,4.3,11.3
secondEntry,Japan,AFC,1.9,4.9,9.1
2,China,AFC,19.5,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4
...,...,...,...,...,...
186,Tonga,OFC,0.0,0.0,0.0
187,Liberia,CAF,0.1,0.0,0.0
188,Palau,OFC,0.0,0.0,0.0
189,Nauru,OFC,0.0,0.0,0.0
190,Niue,OFC,0.0,0.0,0.0

In [7]:
#renaming or setting axis value
dataset.rename_axis("fields", axis='columns')

fields,country,confederation,population_share,tv_audience_share,gdp_weighted_share
0,United States,CONCACAF,4.5,4.3,11.3
1,Japan,AFC,1.9,4.9,9.1
2,China,AFC,19.5,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4
...,...,...,...,...,...
186,Tonga,OFC,0.0,0.0,0.0
187,Liberia,CAF,0.1,0.0,0.0
188,Palau,OFC,0.0,0.0,0.0
189,Nauru,OFC,0.0,0.0,0.0
190,Niue,OFC,0.0,0.0,0.0

In [8]:
dataset1=pd.read_csv("fifa_countries_audience.csv")#191 rows
dataset2=pd.read_csv("olympics.csv")#11 rows

In [9]:
# concat is used when we have same fieds(column names) in dataset
pd.concat([dataset1, dataset2])

,country,confederation,population_share,tv_audience_share,gdp_weighted_share
0,United States,CONCACAF,4.5,4.3,11.3
1,Japan,AFC,1.9,4.9,9.1
2,China,AFC,19.5,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4
...,...,...,...,...,...
6,Italy,UEFA,0.9,2.1,4.0
7,France,UEFA,0.9,2.0,4.0
8,Russia,UEFA,2.1,3.1,3.5
9,Spain,UEFA,0.7,1.8,3.1
10,South Korea,AFC,0.7,1.8,3.0

In [12]:
# join() lets you combine different DataFrame objects which have an index in common.
dataset1=pd.read_csv("fifa_countries_audience.csv")#191rows
dataset2=pd.read_csv("olympics.csv")#11rows
dataset1.join(dataset2 ,lsuffix='country', rsuffix='country')

,countrycountry,confederationcountry,population_sharecountry,tv_audience_sharecountry,gdp_weighted_sharecountry,countrycountry,confederationcountry,population_sharecountry,tv_audience_sharecountry,gdp_weighted_sharecountry
0,United States,CONCACAF,4.5,4.3,11.3,United States,CONCACAF,3.6,3.7,11.3
1,Japan,AFC,1.9,4.9,9.1,Japan,AFC,2.3,4.8,9.1
2,China,AFC,19.5,14.8,7.3,China,AFC,18.6,14.8,7.3
3,Germany,UEFA,1.2,2.9,6.3,Germany,UEFA,1.2,12.9,6.3
4,Brazil,CONMEBOL,2.8,7.1,5.4,Brazil,CONMEBOL,2.8,18.6,5.4
...,...,...,...,...,...,...,...,...,...,...
186,Tonga,OFC,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
187,Liberia,CAF,0.1,0.0,0.0,NaN,NaN,NaN,NaN,NaN
188,Palau,OFC,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
189,Nauru,OFC,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
190,Niue,OFC,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN